version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - .git/
        - action: rebuild
          path: pyproject.toml